image: node:latest

cache:
  paths:
   - node_modules/

before_script:
  - npm install
  - npm -i -g gulp

stages:
  - build_deploy

build_app:
  stage: build
  only:
   - develop
  script:
   - gulp build