image: node:11.10.0

cache:
  paths:
   - node_modules/

before_script:
  - npm install
  - npm i -g gulp

stages:
  - build

build_app:
  stage: build
  only:
   - develop
  script:
   - gulp build
  artifacts:
   paths:
    - build/